### ISSUE TITLE
Filtering project lists

### ISSUE THREAD

**Issue by booski** [dsv-su/resultpress#26]
There will need to be some way of filtering project lists based on project state. This depends on #25 being done.

Since project states are a strict progression (is that certain?), a min-max slider may be appropriate. Another approach would be to collate projects within a listing based on their state, but this may cause difficulty finding a project if its state has changed unexpectedly.

In order to make sure finished projects don't start cluttering things up in a few years, the default filter should hide projects that have reached an end state (finished? maybe an archived state?).

**Comment by PRindby** [comment]
I like the distinction finished/archived - as long as the archived ones are not super hard to access again because then nothing will be moved to archived because "I may need to look at it later and will not find it if it is archived"

**Comment by PRindby** [comment]
Not sure I understand this part **Since project states are a strict progression (is that certain?), a min-max slider may be appropriate.** 

Beyond project stages I would also want to be able to filter on:

- Partner organisation
- Country
- Year: this would probably be many different things I will list the ones I think of below
- Start year
- End year 
- Active in year X 
- Area (so research/transparency/health and so on - I am not up to speed with naming scheme just yet)

I will also involve the SPIDER team to get additional input on filtering.

**Comment by pavelsokolov** [comment]
'Filter by' button should be extended to accept various project fields:
- status
- free text for title/description
- users?
- etc

**Comment by PRindby** [comment]
Discussions in today's meeting covered this in relation to the filter button:

- It needs to show what filter is active
- My projects should be a filter option (then we can remove the menu item called My projects)
- We need to discuss futher the filtering options for other project fields and free text
- The ability to filter on more than one thing - for example Education projects in Uganda or with a certain partner organisation
