### ISSUE TITLE
Ability to log off or change users

### ISSUE THREAD

**Issue by PRindby** [dsv-su/resultpress#50]
There is no log of button. It is needed to change users.

(This is a SSO-related issue. Is it better with a work-around for the few SPIDER users who will need to swap between users?)

**Comment by orkit** [comment]
I will look into this.

**Comment by booski** [comment]
SSO doesn't properly support logging off, so a button to sign out from SSO would be meaningless. However it may be useful to have the ability for users with sufficient rights to impersonate others in a similar way as moodle/drupal allow.

Anything done while impersonating another user must be logged with both the real and the imersonated user information, so that auditability can be maintained.

**Comment by orkit** [comment]
Aha, ok. Is this a function that should be implemented in production or is it only necessary during testing?

**Comment by booski** [comment]
I'd say both - it can be a very good assistance tool as long as the audit trail is maintained.

**Comment by orkit** [comment]
Alright!

**Comment by PRindby** [comment]
Agreed with David that during testing he will work around it. 
It get the point Erik is making - perhaps a nice to have after launch.
