### ISSUE TITLE
Partner information on projects

### ISSUE THREAD

**Issue by PRindby** [dsv-su/resultpress#60]
There are no fields for information about the implementing partner in resultspress. 

We need: 

- organisation name
- contact person (this could be the person reporting and tied to their identity - perhaps invite them when setting up the project?)
- implementing country (maybe possible to add more than one for multisite stuff)

see below for updates after SPIDER input (13 april)

**Comment by booski** [comment]
Partner handling in general probably needs more thought. At the moment I think that partner is basically synonymous with the person who is invited to report on the project. Maybe there needs to be an abstraction layer here, with a partner organization and member accounts bound to it?

Some things to consider:
 - Can an organization be directly associated with a project? As in if there is more than one user from an organization, can we expect that they can always share access rights? Or does access still need to be handled per user?
 - Is there any reason to think partner accounts might be shared between several people? As a matter of policy that shouldn't happen or be allowed, but if the reality is that it is expected to happen then it's better that we take it into account now.
 - What is the function of logging the implementing country? Can it be a free-text field where you can type anything ("Botswana and northern Malawi"), or should it be something more structured that for instance might validate country names or provide suggestions etc?

**Comment by booski** [comment]
Based on today's meeting: 
Country input fields should be implemented as a free-text field that auto-completes based on whatever has previously been saved for that field.

So if we have projects for Botswana and Bolivia, the field should suggest both countries when the user types 'b', and narrow it down based on the following letters typed.

**Comment by booski** [comment]
Re organizations based on today's meeting:

Project partners need to be sorted into organizations, so that there can be seeveral users in the system belonging to the same organization. Partner organizations should be definied in a similar way as program areas.

When inviting a project partner, the inviting spider user must choose an organization that the new user will belong to. 

Questions that need answering:
 - Should projects be connected to partner users or partner organizations? In other words, should a reporting reminder be sent to all the users belonging to a specified org or only a specific person in the org?
 - Should an org have a contact person? This might solve the previous question if the contact person can always be assumed to be the correct person to notify about deadlines etc.

**Comment by PRindby** [comment]
Following today's SPIDER meeting, these are ideas from the SPIDER team.
Here is the input I got. These are my raw notes, will need some refining. 

partner name
contactdetails 
address phone number
project manager
people in the agreement
cfo 
diarenummer
economic reporting? 
country - area 

max two to get updates

**Comment by PRindby** [comment]
Trying to refine the thinking from SPIDER team a bit. These are the parts I think we need to define before going forward

Organisation 
- what is the definition and which information related to it do we put in resultspress
- can more than one organisation be associated with a project? 
- can an organisation be associated with more than one project? (here I will say yes immediately)

Persons (not SPIDERs)
- what information is entered in resultspress
- by whom? (SPIDER pm, a person apply for access or what?)
- any GDPR concerns or stuff we need to inform re processing of personal data?
- can a person be associated with more than one project? 
- Can more than one person be associated to a project?
- can roles be flagged - for example project manager vs CFO

Financial reporting 
- needs some further thinking

Country/area and similiar
Look at the granularity of it and how to get that information in resultspress

Probably more but it is a start

**Comment by booski** [comment]
Organisation: 
 - Info: I sugggest a name and an optional free text description. 
 - Project association: I wouldn't directly associate orgs at all, but let it be done via users. (see below)
 - User association: Each user is associated with a single org. If needed it should be trivial to connect users to more than one org but it would complicate reporting and seems unlikely anyway.

Users: 
 - Invites: Non-spider users already have to be invited by a spider user. Not sure if only certain spiders can invite. 
 - Titles/roles: could be an optional profile field. 
 - Project association: Associating each user with an org would by extension associate any projects that user is involved in with the org. Multiple users from different orgs involved in a project would similarly make multiple orgs involved in a project. Pretty sure there is no limit to number of people in a project.
 - GDPR: There will need to be some boilerplate text to accept when creating a user account, should be trivial.

Countries - The difficulty is in knowing how to meaningfully aggregate. We could keep a list of all countries in the world along with their continents for example. This would allow a project (or maybe activity?) to be associated with a country and by extension with a continent.

Financial reporting should have a lot of the groundwork in place since projects have budget numbers and updates can report spending on a per-activity basis. I would very much not recommend going into further detail in the project budgeting inside resultpress because we would quickly find ourselves re-inventing excel.

**Comment by PRindby** [comment]
> Countries - The difficulty is in knowing how to meaningfully aggregate. We could keep a list of all countries in the world along with their continents for example. This would allow a project (or maybe activity?) to be associated with a country and by extension with a continent.
> 
Some SPIDERs would even wish for regions within a country. Not sure how often that information would be useful. 
The question of how many projects we have/have had in certain countries - or continents does come up every now and then. Absolutely when reporting to Sida, and SU. Could also be a combination of country and program area - say Education projects in Tanzania (or Asia for that matter). 
This site had surprisingly detailed maps. Perhaps possible to figure out where the lists come from? https://mapchart.net/index.html


> Financial reporting should have a lot of the groundwork in place since projects have budget numbers and updates can report spending on a per-activity basis. I would very much not recommend going into further detail in the project budgeting inside resultpress because we would quickly find ourselves re-inventing excel.

Good point. Can partners attach an excel file for the detailed budget reporting in Resultpress? It would keep everything in one place.

**Comment by orkit** [comment]
Partner information is now implemented according to the specification described during our meeting.

- Project partners are organized by organizations, so that there can be several users in the system belonging to the same organization.
- When inviting a project partner, the inviting spider user must choose an organization that the new user will belong to.
- Adding a new organization or searching / editing existing organizations and associating / editing existing users / partners can be done via the admin view.

**Comment by PRindby** [comment]
Seems to be working as intended.
