### ISSUE TITLE
Issue with inviting users 

### ISSUE THREAD

**Issue by PRindby** [dsv-su/resultpress#62]
David has experienced problems with inviting new users. Or perhaps rather to make the account after being invited. 
The new user cannot login - and sytem does not recognize the emailaddress of the invited person. 
I will add screenshots. 

> The invitation function does not work right now. I cant log in with an external account. It cannot find the account but it cant take aninvite that is already taken. 

![image](https://user-images.githubusercontent.com/78147093/108370826-5c0db980-71fd-11eb-895b-15d889bce8f6.png)
![image](https://user-images.githubusercontent.com/78147093/108370847-6465f480-71fd-11eb-93fd-24422c786f38.png)

**Comment by orkit** [comment]
Yes, an invitation has been sent to a test partner but the test partner has not registered in the system. There is an invitation email with a link that has not been answered. Could it be that the invitation email has ended up in the email-trash? Because the test partner has not registered in the system, the test person can not log in, nor change the password.

We will add a function to check which invitations have been sent and possibly resend invitations that havent been replied.

1.) Once the project manager has sent out an invitation, the person must click on the link (or button in the message) - it is not possible to log in or register without doing so because the message contains a security token that ensures that the recipient of the message is the one who registers.
![Screenshot 2021-02-18 at 16 19 35](https://user-images.githubusercontent.com/22212903/108379710-7c8e4180-7206-11eb-98ae-1a3996dfb3cf.png)
![Screenshot 2021-02-18 at 16 20 06](https://user-images.githubusercontent.com/22212903/108379762-8748d680-7206-11eb-9744-6e1dee304777.png)

2.) The reciving partner must click on the button or the link.
![Screenshot 2021-02-18 at 16 30 37](https://user-images.githubusercontent.com/22212903/108380069-cd9e3580-7206-11eb-8e33-0e12ac480932.png)

3.) Once the partner has clicked on the link, you will be sent to the results press with the opportunity to register.
![Screenshot 2021-02-18 at 16 21 46](https://user-images.githubusercontent.com/22212903/108380287-ff170100-7206-11eb-84e4-4278c2ff4366.png)
You can register with a resultpress account or if the partner has a Github, facebook, linkedin or google account they can used that to register.

Once the partner has registered, it can log in and also change the password.

**Comment by orkit** [comment]
I will resend the invitation to david_zilver@

**Comment by PRindby** [comment]
Good added feature. Will it also be possible to retract invitations? (If not then I suspect we can block or suspend persons if necessary)
I suspected some sort of handling error. If this persists I will try to invite myself and see what happens.

**Comment by orkit** [comment]
Yes, I think it would be good to have an admin view for each project owner where you can see which invitations have been sent and where you can resend or delete(=retract) an active invitation. If the user to whom you have sent an invitation has already registered in resultspress, the user can be removed by the program administrator(?). It should also be possible to remove the user from the project without deleting the user from resultpress completely. 

So a _spider_ should be able to: get an overview of all invitations, delete sent invitations, connect other partners who are already registered in resultspress to the project, disconnect partners from the project.
A _program administrator_ should be able to do all of the above but also remove partners completely (or lock without deleting). Something else?
